// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddAddressRequset struct {
	Type         int8   `json:"type" validate:"required,oneof=1 2" label:"地址类型 1=收货地址 2=取件地址"`
	ContactName  string `json:"contact_name" validate:"required,min=2,max=50" label:"联系人姓名"`
	ContactPhone string `json:"contact_phone" validate:"required,len=11" label:"手机号"`
	Building     string `json:"building" validate:"required,max=50" label:"宿舍楼/教学楼"`
	Room         string `json:"room" validate:"required,max=20" label:"房间号"`
	Detail       string `json:"detail" validate:"max=255" label:"详细地址"`
}

type AddressItem struct {
	AddressID    int64  `json:"id"`            // 地址ID
	Type         int8   `json:"type"`          // 地址类型 1=收货地址 2=取件地址
	ContactName  string `json:"contact_name"`  // 联系人姓名
	ContactPhone string `json:"contact_phone"` // 联系电话
	Building     string `json:"building"`      // 宿舍楼/教学楼
	Room         string `json:"room"`          // 房间号
	Detail       string `json:"detail"`        // 详细地址补充说明
	IsDefault    int8   `json:"is_default"`    // 是否默认 1=是 0=否
}

type ApplyRiderRequest struct {
	RealName          string `form:"real_name"`
	StudentNo         string `form:"student_no"`
	IdCardNo          string `form:"id_card_no"`
	DormitoryBuilding string `form:"dormitory_building"`
	DormitoryRoom     string `form:"dormitory_room"`
}

type AuditRiderRequest struct {
	UserID int64  `json:"user_id" validate:"required" label:"用户ID"`
	Result int8   `json:"result" validate:"required,oneof=1 2" label:"审核结果（1=通过，2=拒绝）"`
	Remark string `json:"remark" validate:"max=255" label:"审核备注"`
}

type BaseApplyRiderInfo struct {
	RealName           string `json:"real_name"`
	StudentNo          string `json:"student_no"`
	IDCardNo           string `json:"id_card_no"`
	DormitoryBuilding  string `json:"dormitory_building"`
	DormitoryRoom      string `json:"dormitory_room"`
	CampusCardFrontURL string `json:"campus_card_front_url"`
	CampusCardBackURL  string `json:"campus_card_back_url"`
	Status             string `json:"status"`
	AuditRemark        string `json:"audit_remark"`
}

type CancelOrderRequest struct {
	OrderID int64  `json:"order_id" validate:"required" label:"订单ID"`
	Reason  string `json:"reason" validate:"required,max=255" label:"取消原因"`
}

type ChangePasswordRequest struct {
	OldPassword   string `json:"old_password" validate:"required,min=6,max=20" label:"旧密码"`
	NewPassword   string `json:"new_password" validate:"required,min=6,max=20" label:"新密码"`
	NewRePassword string `json:"new_re_password" validate:"required,eqfield=NewPassword" label:"确认新密码"`
}

type ChangePhoneRequest struct {
	VerifyToken string `json:"verify_token" validate:"required" label:"验证令牌"`
	VerifyType  int    `json:"verify_type" validate:"required,oneof=1 2"` // 1=密码 2=旧手机验证码
	Password    string `json:"password,omitempty" validate:"omitempty,min=6,max=20" label:"密码"`
	OldCode     string `json:"old_code,optional" label:"旧手机验证码"`
}

type ConfirmDeliveryRequest struct {
	OrderID int64 `json:"order_id" validate:"required" label:"订单ID"`
}

type CreateOrderRequest struct {
	OrderType         int8    `json:"order_type" validate:"required,oneof=1 2" label:"订单类型"`
	PickupAddressID   int64   `json:"pickup_address_id" validate:"required" label:"取件地址ID"`
	DeliveryAddressID int64   `json:"delivery_address_id" validate:"required" label:"送达地址ID"`
	RewardAmount      float64 `json:"reward_amount" validate:"required,gt=0" label:"悬赏金额"`
	Remark            string  `json:"remark" validate:"max=255" label:"订单备注"`
}

type CreateOrderResponse struct {
	OrderID           int64  `json:"order_id"`
	OrderNo           string `json:"order_no"`
	Status            int8   `json:"status"`
	PaymentStatus     int8   `json:"payment_status"`
	PaymentStatusText string `json:"payment_status_text"`
}

type CreateReviewRequest struct {
	OrderID int64  `json:"order_id" validate:"required" label:"订单ID"`
	Score   int8   `json:"score" validate:"required,gte=1,lte=5" label:"评分"`
	Content string `json:"content" validate:"max=255" label:"评价内容"`
}

type DeleteAddressRequest struct {
	AddressID int64 `path:"id" validate:"required" label:"地址ID"`
}

type DeliverOrderRequest struct {
	OrderID int64 `json:"order_id" validate:"required" label:"订单ID"`
}

type DetailApplyRiderInfo struct {
	ID                 int64  `json:"id"`
	UserID             int64  `json:"user_id"`
	RealName           string `json:"real_name"`
	StudentNo          string `json:"student_no"`
	IDCardNo           string `json:"id_card_no"`
	DormitoryBuilding  string `json:"dormitory_building"`
	DormitoryRoom      string `json:"dormitory_room"`
	CampusCardFrontURL string `json:"campus_card_front_url"`
	CampusCardBackURL  string `json:"campus_card_back_url"`
	Status             int8   `json:"status"`
	AuditRemark        string `json:"audit_remark"`
	UpdatedAt          string `json:"updated_at"`
}

type ForgetPasswordRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	VerifyCode string `json:"code" validate:"required,min=6,max=6" label:"验证码"`
}

type ForgetPasswordResponse struct {
	ResetToken string `json:"reset_token"`
}

type GenerateVerifyCodeRequest struct {
	Phone string `json:"phone" validate:"required" label:"手机号"`
}

type GenerateVerifyCodeResponse struct {
	Code string `json:"code"`
}

type GetAddressDetailRequest struct {
	AddressID int64 `path:"id" validate:"required" label:"地址ID"`
}

type GetAddressListRequest struct {
	Type int8 `form:"type" validate:"required,oneof=1 2" label:"地址类型 1=收货地址 2=取件地址；"`
}

type GetAvailableOrderListRequest struct {
	Page      int     `form:"page,optional"`
	Size      int     `form:"size,optional"`
	SortBy    string  `form:"sort_by,optional"`
	SortOrder string  `form:"order,optional"`
	MinReward float64 `form:"min_reward,optional"`
	MaxReward float64 `form:"max_reward,optional"`
}

type GetAvailableOrderListResponse struct {
	Total int64       `json:"total"`
	List  []OrderItem `json:"list"`
}

type GetAvatarRequest struct {
	UserID int64 `path:"user_id" label:"用户ID"`
}

type GetOrderDetailRequest struct {
	OrderID int64 `path:"id" validate:"required" label:"订单ID"`
}

type GetOrderLogResponse struct {
	List []OrderLogItem `json:"list"`
}

type GetRiderApplyListRequest struct {
	Status int8 `form:"status,optional"`    // 不传则默认为某个特定值（如 -1）
	Page   int  `form:"page,optional"`      // 不传默认为 1
	Size   int  `form:"page_size,optional"` // 不传默认为 10
}

type GetRiderApplyListResponse struct {
	ApplyList []DetailApplyRiderInfo `json:"apply_list"`
	Total     int64                  `json:"total"`
}

type GetRiderOrderListRequest struct {
	Status int8 `form:"status,optional"`
	Page   int  `form:"page,optional"`
	Size   int  `form:"size,optional"`
}

type GetRiderOrderListResponse struct {
	Total int64       `json:"total"`
	List  []OrderItem `json:"list"`
}

type GetUserOrderListRequest struct {
	Status int8 `form:"status,optional"`
	Page   int  `form:"page,optional"`
	Size   int  `form:"size,optional"`
}

type GetUserOrderListResponse struct {
	Total int64       `json:"total"`
	List  []OrderItem `json:"list"`
}

type GrabOrderRequest struct {
	OrderID int64 `json:"order_id" validate:"required" label:"订单ID"`
}

type LoginResponse struct {
	Token    string `json:"token"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type LoginWithPasswordRequest struct {
	Phone    string `json:"phone" validate:"required" label:"手机号"`
	Password string `json:"password" validate:"required,min=6,max=20" label:"密码"`
}

type LoginWithVerifyCodeRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	VerifyCode string `json:"code" validate:"required,min=6,max=6" label:"验证码"`
}

type OrderItem struct {
	ID                int64   `json:"id"`
	OrderNo           string  `json:"order_no"`
	UserID            int64   `json:"user_id"`
	RiderID           *int64  `json:"rider_id"`
	OrderType         int8    `json:"order_type"`
	PickupAddressID   int64   `json:"pickup_address_id"`
	DeliveryAddressID int64   `json:"delivery_address_id"`
	RewardAmount      float64 `json:"reward_amount"`
	Status            int8    `json:"status"`
	StatusText        string  `json:"status_text"`
	PaymentStatus     int8    `json:"payment_status"`
	PaymentStatusText string  `json:"payment_status_text"`
	Remark            string  `json:"remark"`
	CancelReason      string  `json:"cancel_reason"`
	CreatedAt         string  `json:"created_at"`
	PaidAt            *string `json:"paid_at"`
	AcceptedAt        *string `json:"accepted_at"`
	PickedUpAt        *string `json:"picked_up_at"`
	DeliveredAt       *string `json:"delivered_at"`
	CancelledAt       *string `json:"cancelled_at"`
	RefundedAt        *string `json:"refunded_at"`
}

type OrderLogItem struct {
	ID           int64  `json:"id"`
	FromStatus   int8   `json:"from_status"`
	ToStatus     int8   `json:"to_status"`
	OperatorType int8   `json:"operator_type"`
	OperatorID   int64  `json:"operator_id"`
	Remark       string `json:"remark"`
	CreatedAt    string `json:"created_at"`
}

type PayOrderRequest struct {
	OrderID int64 `json:"order_id" validate:"required" label:"订单ID"`
}

type PickupOrderRequest struct {
	OrderID int64 `json:"order_id" validate:"required" label:"订单ID"`
}

type RegisterRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	Password   string `json:"password" validate:"required,min=6,max=20" label:"密码"`
	RePassword string `json:"re_password" validate:"required,eqfield=Password" label:"确认密码"`
	VerifyCode string `json:"code" validate:"required" label:"验证码"`
}

type RegisterResponse struct {
	Token    string `json:"token"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type ResetPasswordRequest struct {
	Phone         string `json:"phone" validate:"required" label:"手机号"`
	ResetToken    string `form:"reset_token" validate:"required" label:"重置凭证"`
	NewPassword   string `json:"new_password" validate:"required,min=6,max=20" label:"密码"`
	NewRePassword string `json:"new_re_password" validate:"required,eqfield=NewPassword" label:"确认密码"`
}

type RiderCancelOrderRequest struct {
	OrderID int64  `json:"order_id" validate:"required" label:"订单ID"`
	Reason  string `json:"reason" validate:"required,max=255" label:"取消原因"`
}

type SendNewPhoneCodeRequest struct {
	NewPhone string `json:"new_phone" validate:"required"`
}

type SetDefaultAddressRequest struct {
	AddressID int64 `path:"id" validate:"required" label:"地址ID"`
}

type UpdateAddressRequest struct {
	AddressID    int64  `path:"id" validate:"required" label:"地址ID"`
	ContactName  string `json:"contact_name" validate:"required,min=2,max=50" label:"联系人姓名"`
	ContactPhone string `json:"contact_phone" validate:"required,len=11" label:"手机号"`
	Building     string `json:"building" validate:"required,max=50" label:"宿舍楼/教学楼"`
	Room         string `json:"room" validate:"required,max=20" label:"房间号"`
	Detail       string `json:"detail" validate:"max=255" label:"详细地址"`
}

type UpdateAvatarResponse struct {
	AvatarUrl string `json:"avatarUrl"`
}

type UpdateProfileRequest struct {
	Nickname string `json:"nickname" validate:"required" label:"昵称"`
	Gender   int8   `json:"gender" validate:"required,oneof=0 1 2" label:"性别，0未知，1男，2女"`
}

type UserProfileResponse struct {
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Gender   int8   `json:"gender"`
}

type VerifyNewPhoneRequest struct {
	NewPhone string `json:"new_phone" validate:"required" label:"新手机号"`
	Code     string `json:"code" validate:"required" validate:"len=6" label:"验证码"`
}

type VerifyNewPhoneResponse struct {
	VerifyToken string `json:"verify_token"`
}
