// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddAddressRequset struct {
	Type         int8   `json:"type" validate:"required,oneof=1 2" label:"地址类型 1=收货地址 2=取件地址"`
	ContactName  string `json:"contact_name" validate:"required,min=2,max=50" label:"联系人姓名"`
	ContactPhone string `json:"contact_phone" validate:"required,len=11" label:"手机号"`
	Building     string `json:"building" validate:"required,max=50" label:"宿舍楼/教学楼"`
	Room         string `json:"room" validate:"required,max=20" label:"房间号"`
	Detail       string `json:"detail" validate:"max=255" label:"详细地址"`
}

type AddressItem struct {
	AddressID    int64  `json:"id"`            // 地址ID
	Type         int8   `json:"type"`          // 地址类型 1=收货地址 2=取件地址
	ContactName  string `json:"contact_name"`  // 联系人姓名
	ContactPhone string `json:"contact_phone"` // 联系电话
	Building     string `json:"building"`      // 宿舍楼/教学楼
	Room         string `json:"room"`          // 房间号
	Detail       string `json:"detail"`        // 详细地址补充说明
	IsDefault    int8   `json:"is_default"`    // 是否默认 1=是 0=否
}

type ApplyRiderRequest struct {
	RealName          string `form:"real_name"`
	StudentNo         string `form:"student_no"`
	IdCardNo          string `form:"id_card_no"`
	DormitoryBuilding string `form:"dormitory_building"`
	DormitoryRoom     string `form:"dormitory_room"`
}

type BaseApplyRiderInfo struct {
	RealName           string `json:"real_name"`
	StudentNo          string `json:"student_no"`
	IDCardNo           string `json:"id_card_no"`
	DormitoryBuilding  string `json:"dormitory_building"`
	DormitoryRoom      string `json:"dormitory_room"`
	CampusCardFrontURL string `json:"campus_card_front_url"`
	CampusCardBackURL  string `json:"campus_card_back_url"`
	Status             int8   `json:"status"`
	AuditRemark        string `json:"audit_remark"`
}

type ChangePasswordRequest struct {
	OldPassword   string `json:"old_password" validate:"required,min=6,max=20" label:"旧密码"`
	NewPassword   string `json:"new_password" validate:"required,min=6,max=20" label:"新密码"`
	NewRePassword string `json:"new_re_password" validate:"required,eqfield=NewPassword" label:"确认新密码"`
}

type DeleteAddressRequest struct {
	AddressID int64 `path:"id" validate:"required" label:"地址ID"`
}

type DetailApplyRiderInfo struct {
	ID                 int64  `json:"id"`
	UserID             int64  `json:"user_id"`
	RealName           string `json:"real_name"`
	StudentNo          string `json:"student_no"`
	IDCardNo           string `json:"id_card_no"`
	DormitoryBuilding  string `json:"dormitory_building"`
	DormitoryRoom      string `json:"dormitory_room"`
	CampusCardFrontURL string `json:"campus_card_front_url"`
	CampusCardBackURL  string `json:"campus_card_back_url"`
	Status             int8   `json:"status"`
	AuditRemark        string `json:"audit_remark"`
	UpdatedAt          string `json:"updated_at"`
}

type ForgetPasswordRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	VerifyCode string `json:"code" validate:"required,min=6,max=6" label:"验证码"`
}

type ForgetPasswordResponse struct {
	ResetToken string `json:"reset_token"`
}

type GenerateVerifyCodeRequest struct {
	Phone string `json:"phone" validate:"required" label:"手机号"`
}

type GenerateVerifyCodeResponse struct {
	Code string `json:"code"`
}

type GetAddressDetailRequest struct {
	AddressID int64 `path:"id" validate:"required" label:"地址ID"`
}

type GetAddressListRequest struct {
	Type int8 `form:"type" validate:"required,oneof=1 2" label:"地址类型 1=收货地址 2=取件地址；"`
}

type GetAvatarRequest struct {
	UserID int64 `path:"user_id"`
}

type GetRiderApplyListRequest struct {
	Status int8 `form:"status,optional"`    // 不传则默认为某个特定值（如 -1）
	Page   int  `form:"page,optional"`      // 不传默认为 1
	Size   int  `form:"page_size,optional"` // 不传默认为 10
}

type GetRiderApplyListResponse struct {
	ApplyList []DetailApplyRiderInfo `json:"apply_list"`
	Total     int64                  `json:"total"`
}

type LoginResponse struct {
	Token    string `json:"token"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type LoginWithPasswordRequest struct {
	Phone    string `json:"phone" validate:"required" label:"手机号"`
	Password string `json:"password" validate:"required,min=6,max=20" label:"密码"`
}

type LoginWithVerifyCodeRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	VerifyCode string `json:"code" validate:"required,min=6,max=6" label:"验证码"`
}

type RegisterRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	Password   string `json:"password" validate:"required,min=6,max=20" label:"密码"`
	RePassword string `json:"re_password" validate:"required,eqfield=Password" label:"确认密码"`
	VerifyCode string `json:"code" validate:"required" label:"验证码"`
}

type RegisterResponse struct {
	Token    string `json:"token"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type ResetPasswordRequest struct {
	Phone         string `json:"phone" validate:"required" label:"手机号"`
	ResetToken    string `form:"reset_token" validate:"required" label:"重置凭证"`
	NewPassword   string `json:"new_password" validate:"required,min=6,max=20" label:"密码"`
	NewRePassword string `json:"new_re_password" validate:"required,eqfield=NewPassword" label:"确认密码"`
}

type SetDefaultAddressRequest struct {
	AddressID int64 `path:"id" validate:"required" label:"地址ID"`
}

type UpdateAddressRequest struct {
	AddressID    int64  `path:"id" validate:"required" label:"地址ID"`
	ContactName  string `json:"contact_name" validate:"required,min=2,max=50" label:"联系人姓名"`
	ContactPhone string `json:"contact_phone" validate:"required,len=11" label:"手机号"`
	Building     string `json:"building" validate:"required,max=50" label:"宿舍楼/教学楼"`
	Room         string `json:"room" validate:"required,max=20" label:"房间号"`
	Detail       string `json:"detail" validate:"max=255" label:"详细地址"`
}

type UpdateAvatarResponse struct {
	AvatarUrl string `json:"avatarUrl"`
}

type UpdateProfileRequest struct {
	Nickname string `json:"nickname" validate:"required" label:"昵称"`
	Gender   int8   `json:"gender" validate:"required,oneof=0 1 2" label:"性别，0未知，1男，2女"`
}

type UserProfileResponse struct {
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Gender   int8   `json:"gender"`
}
