// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddAddressRequset struct {
	ContactName  string `json:"contact_name" validate:"required,min=2,max=50" label:"联系人姓名"`
	ContactPhone string `json:"contact_phone" validate:"required,len=11" label:"手机号"`
	Building     string `json:"building" validate:"required,max=50" label:"宿舍楼/教学楼"`
	Room         string `json:"room" validate:"required,max=20" label:"房间号"`
}

type AddressItem struct {
	AddressID    uint64 `json:"id"`            // 地址ID
	ContactName  string `json:"contact_name"`  // 联系人姓名
	ContactPhone string `json:"contact_phone"` // 联系电话
	Building     string `json:"building"`      // 宿舍楼/教学楼
	Room         string `json:"room"`          // 房间号
	IsDefault    int8   `json:"is_default"`    // 是否默认 1=是 0=否
}

type DeleteAddressRequest struct {
	AddressID uint64 `path:"id" validate:"required" label:"地址ID"`
}

type ForgetPasswordRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	VerifyCode string `json:"code" validate:"required,min=6,max=6" label:"验证码"`
}

type ForgetPasswordResponse struct {
	ResetToken string `json:"reset_token"`
}

type GenerateVerifyCodeRequest struct {
	Phone string `json:"phone" validate:"required" label:"手机号"`
}

type GenerateVerifyCodeResponse struct {
	Code string `json:"code"`
}

type GetAddressDetailRequest struct {
	AddressID uint64 `path:"id" validate:"required" label:"地址ID"`
}

type LoginResponse struct {
	Token    string `json:"token"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type LoginWithPasswordRequest struct {
	Phone    string `json:"phone" validate:"required" label:"手机号"`
	Password string `json:"password" validate:"required,min=6,max=20" label:"密码"`
}

type LoginWithVerifyCodeRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	VerifyCode string `json:"code" validate:"required,min=6,max=6" label:"验证码"`
}

type RegisterRequest struct {
	Phone      string `json:"phone" validate:"required" label:"手机号"`
	Password   string `json:"password" validate:"required,min=6,max=20" label:"密码"`
	RePassword string `json:"re_password" validate:"required,eqfield=Password" label:"确认密码"`
	VerifyCode string `json:"code" validate:"required" label:"验证码"`
}

type RegisterResponse struct {
	Token    string `json:"token"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type ResetPasswordRequest struct {
	Phone         string `json:"phone" validate:"required" label:"手机号"`
	ResetToken    string `form:"reset_token" validate:"required" label:"重置凭证"`
	NewPassword   string `json:"new_password" validate:"required,min=6,max=20" label:"密码"`
	NewRePassword string `json:"new_re_password" validate:"required,eqfield=NewPassword" label:"确认密码"`
}

type SetDefaultAddressRequest struct {
	AddressID uint64 `path:"id" validate:"required" label:"地址ID"`
}

type UpdateAddressRequest struct {
	AddressID    uint64 `path:"id" validate:"required" label:"地址ID"`
	ContactName  string `json:"contact_name" validate:"required,min=2,max=50" label:"联系人姓名"`
	ContactPhone string `json:"contact_phone" validate:"required,len=11" label:"手机号"`
	Building     string `json:"building" validate:"required,max=50" label:"宿舍楼/教学楼"`
	Room         string `json:"room" validate:"required,max=20" label:"房间号"`
}
