// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	address "CampusTake/internal/handler/address"
	adminrider "CampusTake/internal/handler/admin/rider"
	auth "CampusTake/internal/handler/auth"
	orderrider "CampusTake/internal/handler/order/rider"
	orderuser "CampusTake/internal/handler/order/user"
	rider "CampusTake/internal/handler/rider"
	userphone "CampusTake/internal/handler/user/phone"
	userprofile "CampusTake/internal/handler/user/profile"
	"CampusTake/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: address.AddAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/default/:id",
					Handler: address.SetDefaultAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/delete/:id",
					Handler: address.DeleteAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail/:id",
					Handler: address.GetAddressDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: address.GetAddressListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/update/:id",
					Handler: address.UpdateAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/address"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware, serverCtx.AdminCheck},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/apply",
					Handler: adminrider.GetRiderApplyListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/audit",
					Handler: adminrider.AuditRiderHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/rider"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/forgetpassword",
				Handler: auth.ForgetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/password",
				Handler: auth.LoginWithPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/verifycode",
				Handler: auth.LoginWithVerifyCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resetpassword",
				Handler: auth.ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verifycode",
				Handler: auth.GenerateVerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/changepassword",
					Handler: auth.ChangePasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware, serverCtx.RiderCheck},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/available",
					Handler: orderrider.GetAvailableOrderListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/deliver",
					Handler: orderrider.DeliverOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/grab",
					Handler: orderrider.GrabOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: orderrider.GetRiderOrderListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pickup",
					Handler: orderrider.PickupOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/rider/order"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/apply-cancel",
					Handler: orderuser.ApplyCancelOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: orderuser.CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail/:id",
					Handler: orderuser.GetOrderDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: orderuser.GetUserOrderListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pay",
					Handler: orderuser.PayOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/review",
					Handler: orderuser.CreateReviewHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/order"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/apply",
					Handler: rider.ApplyRiderHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/cancel",
					Handler: rider.CancelApplyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/status",
					Handler: rider.GetApplyStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/rider"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/confirm",
					Handler: userphone.ChangePhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/send-new-code",
					Handler: userphone.SendNewPhoneCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/send-old-code",
					Handler: userphone.SendOldPhoneCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/verify-new",
					Handler: userphone.VerifyNewPhoneHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user/phone"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/avatar/:user_id",
				Handler: userprofile.GetAvatarHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/avatar",
					Handler: userprofile.UpdateAvatarHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/profile",
					Handler: userprofile.GetProfileHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/profile",
					Handler: userprofile.UpdateProfileHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)
}
