// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	address "CampusTake/internal/handler/address"
	auth "CampusTake/internal/handler/auth"
	"CampusTake/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/add",
					Handler: address.AddAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/default/:id",
					Handler: address.SetDefaultAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/delete/:id",
					Handler: address.DeleteAddressHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/detail/:id",
					Handler: address.GetAddressDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: address.GetAddressListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/update/:id",
					Handler: address.UpdateAddressHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/address"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/forgetpassword",
				Handler: auth.ForgetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/password",
				Handler: auth.LoginWithPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/verifycode",
				Handler: auth.LoginWithVerifyCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resetpassword",
				Handler: auth.ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verifycode",
				Handler: auth.GenerateVerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
